title: iTowns
email: itowns@ign.fr
description: >- # this means to ignore newlines until "baseurl:"
  iTowns is a JS/WebGL framework for 3D geospatial data visualization.

baseurl: ""
url: "https://www.itowns-project.org/"

github_username: iTowns


sass:
  style: compressed
  sourcemap: development

collections:
  modals:
    output: false
    permalink: /modals/:name
